<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * AlbumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumRepository extends EntityRepository
{

    /**
     * Get all albums from database and add first 10 images of album to each album
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function findAllWithImages()
    {
        $query  = $this->getEntityManager()->createQuery('
          SELECT a.id, a.name from AppBundle:Album a order by a.id
        ');
        $albums = $query->getResult();

        $query = $this->getEntityManager()->createQuery('
              select i.id, IDENTITY(i.album) as album_id, i.filename
                from AppBundle:Image i
              where (
                select count(im.id) from AppBundle:Image as im
                where IDENTITY(im.album) = IDENTITY(i.album) and im.id <= i.id
              ) <= 10 order by i.id
        ');
        $images = $query->getResult();

        foreach ($albums as &$album)
        {
            $album['images'] = [];
            foreach ($images as $image) {
                if ($image['album_id'] == $album['id']) {
                    $album['images'][] = $image;
                }
            }
        }

        return $albums;
    }



    public function getAlbumImagesQuery($album_id)
    {
        return $this->getEntityManager()->createQuery(
            "SELECT i FROM AppBundle:Image i where i.albumId = :album_id"
        )->setParameter('album_id', $album_id);
    }
}
